// Code generated by SQLBoiler 4.12.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CharacterR     string
	Game           string
	Model          string
	ModelCharacter string
	Player         string
	User           string
	UserStatistics string
}{
	CharacterR:     "CharacterR",
	Game:           "Game",
	Model:          "Model",
	ModelCharacter: "ModelCharacter",
	Player:         "Player",
	User:           "User",
	UserStatistics: "UserStatistics",
}
